export const educationCategories = [
  { label: "Arts and Humanities" },
  { label: "Business and Management" },
  { label: "Computer Science and IT" },
  { label: "Education and Teaching" },
  { label: "Engineering and Technology" },
  { label: "Health and Medicine" },
  { label: "Law and Legal Studies" },
  { label: "Mathematics and Statistics" },
  { label: "Natural Sciences" },
  { label: "Social Sciences" },
  { label: "Agriculture and Environmental Sciences" },
  { label: "Architecture and Construction" },
  { label: "Communications and Media" },
  { label: "Economics and Finance" },
  { label: "Hospitality and Tourism" },
  { label: "Languages and Linguistics" },
  { label: "Philosophy and Religion" },
  { label: "Political Science and International Relations" },
  { label: "Psychology" },
  { label: "Public Administration and Policy" },
  { label: "Vocational and Technical Education" },
  { label: "Sports and Physical Education" },
  { label: "Transportation and Logistics" },
];

export const languages = [
  { code: "en", label: "English" },
  { code: "fr", label: "French" },
  { code: "it", label: "Italian" },
  { code: "pt", label: "Portuguese" },
  { code: "qu", label: "Quechua" },
  { code: "es", label: "Spanish" },
];

export const educationSubCategories = {
  "Arts and Humanities": [
    { label: "History" },
    { label: "Philosophy" },
    { label: "Literature" },
    { label: "Visual Arts" },
    { label: "Performing Arts" },
    { label: "Cultural Studies" },
    { label: "Religious Studies" },
  ],
  "Business and Management": [
    { label: "Accounting" },
    { label: "Finance" },
    { label: "Marketing" },
    { label: "Human Resource Management" },
    { label: "Entrepreneurship" },
    { label: "Operations Management" },
    { label: "Project Management" },
  ],
  "Computer Science and IT": [
    { label: "Software Development" },
    { label: "Cybersecurity" },
    { label: "Artificial Intelligence" },
    { label: "Data Science" },
    { label: "Networking" },
    { label: "Web Development" },
    { label: "IT Support" },
  ],
  "Education and Teaching": [
    { label: "Early Childhood Education" },
    { label: "Primary Education" },
    { label: "Secondary Education" },
    { label: "Special Education" },
    { label: "Educational Leadership" },
    { label: "Curriculum Design" },
  ],
  "Engineering and Technology": [
    { label: "Mechanical Engineering" },
    { label: "Electrical Engineering" },
    { label: "Civil Engineering" },
    { label: "Chemical Engineering" },
    { label: "Computer Engineering" },
    { label: "Robotics" },
    { label: "Mechatronics" },
  ],
  "Health and Medicine": [
    { label: "Medicine" },
    { label: "Nursing" },
    { label: "Pharmacy" },
    { label: "Public Health" },
    { label: "Dentistry" },
    { label: "Nutrition" },
    { label: "Physical Therapy" },
  ],
  "Law and Legal Studies": [
    { label: "Civil Law" },
    { label: "Criminal Law" },
    { label: "International Law" },
    { label: "Corporate Law" },
    { label: "Human Rights Law" },
    { label: "Environmental Law" },
  ],
  "Mathematics and Statistics": [
    { label: "Pure Mathematics" },
    { label: "Applied Mathematics" },
    { label: "Statistics" },
    { label: "Actuarial Science" },
    { label: "Mathematical Modelling" },
  ],
  "Natural Sciences": [
    { label: "Biology" },
    { label: "Chemistry" },
    { label: "Physics" },
    { label: "Earth Sciences" },
    { label: "Astronomy" },
    { label: "Environmental Science" },
  ],
  "Social Sciences": [
    { label: "Sociology" },
    { label: "Anthropology" },
    { label: "Geography" },
    { label: "Political Science" },
    { label: "Criminology" },
  ],
  "Agriculture and Environmental Sciences": [
    { label: "Agronomy" },
    { label: "Horticulture" },
    { label: "Animal Science" },
    { label: "Forestry" },
    { label: "Environmental Management" },
    { label: "Sustainable Agriculture" },
  ],
  "Architecture and Construction": [
    { label: "Architecture" },
    { label: "Urban Planning" },
    { label: "Construction Management" },
    { label: "Structural Design" },
    { label: "Interior Design" },
  ],
  "Communications and Media": [
    { label: "Journalism" },
    { label: "Public Relations" },
    { label: "Media Studies" },
    { label: "Film and Television" },
    { label: "Digital Media" },
  ],
  "Economics and Finance": [
    { label: "Microeconomics" },
    { label: "Macroeconomics" },
    { label: "Banking" },
    { label: "Investment" },
    { label: "Financial Planning" },
  ],
  "Hospitality and Tourism": [
    { label: "Hotel Management" },
    { label: "Travel and Tourism" },
    { label: "Event Management" },
    { label: "Culinary Arts" },
  ],
  "Languages and Linguistics": [
    { label: "Applied Linguistics" },
    { label: "Translation and Interpretation" },
    { label: "Foreign Languages" },
    { label: "Syntax and Semantics" },
  ],
  "Philosophy and Religion": [
    { label: "Ethics" },
    { label: "Metaphysics" },
    { label: "World Religions" },
    { label: "Theology" },
  ],
  "Political Science and International Relations": [
    { label: "Comparative Politics" },
    { label: "International Politics" },
    { label: "Public Policy" },
    { label: "Global Studies" },
  ],
  Psychology: [
    { label: "Clinical Psychology" },
    { label: "Counseling Psychology" },
    { label: "Developmental Psychology" },
    { label: "Cognitive Psychology" },
    { label: "Industrial-Organizational Psychology" },
  ],
  "Public Administration and Policy": [
    { label: "Public Policy" },
    { label: "Government Administration" },
    { label: "Urban Affairs" },
    { label: "Nonprofit Management" },
  ],
  "Vocational and Technical Education": [
    { label: "Welding" },
    { label: "Plumbing" },
    { label: "Automotive Technology" },
    { label: "Electrical Installation" },
    { label: "Carpentry" },
  ],
  "Sports and Physical Education": [
    { label: "Sports Coaching" },
    { label: "Physical Fitness" },
    { label: "Kinesiology" },
    { label: "Recreational Therapy" },
  ],
  "Transportation and Logistics": [
    { label: "Supply Chain Management" },
    { label: "Logistics" },
    { label: "Maritime Transportation" },
    { label: "Aviation Management" },
  ],
};
