export const educationCategories = [
  { label: "Arts and Humanities" },
  { label: "Business and Management" },
  { label: "Computer Science and IT" },
  { label: "Education and Teaching" },
  { label: "Engineering and Technology" },
  { label: "Health and Medicine" },
  { label: "Law and Legal Studies" },
  { label: "Mathematics and Statistics" },
  { label: "Natural Sciences" },
  { label: "Social Sciences" },
  { label: "Agriculture and Environmental Sciences" },
  { label: "Architecture and Construction" },
  { label: "Communications and Media" },
  { label: "Economics and Finance" },
  { label: "Hospitality and Tourism" },
  { label: "Languages and Linguistics" },
  { label: "Philosophy and Religion" },
  { label: "Political Science and International Relations" },
  { label: "Psychology" },
  { label: "Public Administration and Policy" },
  { label: "Vocational and Technical Education" },
  { label: "Sports and Physical Education" },
  { label: "Transportation and Logistics" },
];

export const languages = [
  { code: "ab", label: "Abkhaz" },
  { code: "aa", label: "Afar" },
  { code: "af", label: "Afrikaans" },
  { code: "ak", label: "Akan" },
  { code: "sq", label: "Albanian" },
  { code: "am", label: "Amharic" },
  { code: "ar", label: "Arabic" },
  { code: "an", label: "Aragonese" },
  { code: "hy", label: "Armenian" },
  { code: "as", label: "Assamese" },
  { code: "av", label: "Avaric" },
  { code: "ae", label: "Avestan" },
  { code: "ay", label: "Aymara" },
  { code: "az", label: "Azerbaijani" },
  { code: "bm", label: "Bambara" },
  { code: "ba", label: "Bashkir" },
  { code: "eu", label: "Basque" },
  { code: "be", label: "Belarusian" },
  { code: "bn", label: "Bengali" },
  { code: "bh", label: "Bihari" },
  { code: "bi", label: "Bislama" },
  { code: "bs", label: "Bosnian" },
  { code: "br", label: "Breton" },
  { code: "bg", label: "Bulgarian" },
  { code: "my", label: "Burmese" },
  { code: "ca", label: "Catalan" },
  { code: "ch", label: "Chamorro" },
  { code: "ce", label: "Chechen" },
  { code: "ny", label: "Chichewa" },
  { code: "zh", label: "Chinese" },
  { code: "cv", label: "Chuvash" },
  { code: "kw", label: "Cornish" },
  { code: "co", label: "Corsican" },
  { code: "cr", label: "Cree" },
  { code: "hr", label: "Croatian" },
  { code: "cs", label: "Czech" },
  { code: "da", label: "Danish" },
  { code: "dv", label: "Divehi" },
  { code: "nl", label: "Dutch" },
  { code: "dz", label: "Dzongkha" },
  { code: "en", label: "English" },
  { code: "eo", label: "Esperanto" },
  { code: "et", label: "Estonian" },
  { code: "ee", label: "Ewe" },
  { code: "fo", label: "Faroese" },
  { code: "fj", label: "Fijian" },
  { code: "fi", label: "Finnish" },
  { code: "fr", label: "French" },
  { code: "ff", label: "Fula" },
  { code: "gl", label: "Galician" },
  { code: "ka", label: "Georgian" },
  { code: "de", label: "German" },
  { code: "el", label: "Greek" },
  { code: "gn", label: "Guaraní" },
  { code: "gu", label: "Gujarati" },
  { code: "ht", label: "Haitian Creole" },
  { code: "ha", label: "Hausa" },
  { code: "he", label: "Hebrew" },
  { code: "hz", label: "Herero" },
  { code: "hi", label: "Hindi" },
  { code: "ho", label: "Hiri Motu" },
  { code: "hu", label: "Hungarian" },
  { code: "ia", label: "Interlingua" },
  { code: "id", label: "Indonesian" },
  { code: "ie", label: "Interlingue" },
  { code: "ga", label: "Irish" },
  { code: "ig", label: "Igbo" },
  { code: "ik", label: "Inupiaq" },
  { code: "io", label: "Ido" },
  { code: "is", label: "Icelandic" },
  { code: "it", label: "Italian" },
  { code: "iu", label: "Inuktitut" },
  { code: "ja", label: "Japanese" },
  { code: "jv", label: "Javanese" },
  { code: "kl", label: "Kalaallisut" },
  { code: "kn", label: "Kannada" },
  { code: "kr", label: "Kanuri" },
  { code: "ks", label: "Kashmiri" },
  { code: "kk", label: "Kazakh" },
  { code: "km", label: "Khmer" },
  { code: "ki", label: "Kikuyu" },
  { code: "rw", label: "Kinyarwanda" },
  { code: "ky", label: "Kyrgyz" },
  { code: "kv", label: "Komi" },
  { code: "kg", label: "Kongo" },
  { code: "ko", label: "Korean" },
  { code: "ku", label: "Kurdish" },
  { code: "kj", label: "Kwanyama" },
  { code: "la", label: "Latin" },
  { code: "lb", label: "Luxembourgish" },
  { code: "lg", label: "Ganda" },
  { code: "li", label: "Limburgish" },
  { code: "ln", label: "Lingala" },
  { code: "lo", label: "Lao" },
  { code: "lt", label: "Lithuanian" },
  { code: "lu", label: "Luba-Katanga" },
  { code: "lv", label: "Latvian" },
  { code: "gv", label: "Manx" },
  { code: "mk", label: "Macedonian" },
  { code: "mg", label: "Malagasy" },
  { code: "ms", label: "Malay" },
  { code: "ml", label: "Malayalam" },
  { code: "mt", label: "Maltese" },
  { code: "mi", label: "Māori" },
  { code: "mr", label: "Marathi" },
  { code: "mh", label: "Marshallese" },
  { code: "mn", label: "Mongolian" },
  { code: "na", label: "Nauru" },
  { code: "nv", label: "Navajo" },
  { code: "nb", label: "Norwegian Bokmål" },
  { code: "nd", label: "North Ndebele" },
  { code: "ne", label: "Nepali" },
  { code: "ng", label: "Ndonga" },
  { code: "nn", label: "Norwegian Nynorsk" },
  { code: "no", label: "Norwegian" },
  { code: "ii", label: "Nuosu" },
  { code: "nr", label: "South Ndebele" },
  { code: "oc", label: "Occitan" },
  { code: "oj", label: "Ojibwe" },
  { code: "cu", label: "Old Church Slavonic" },
  { code: "om", label: "Oromo" },
  { code: "or", label: "Oriya" },
  { code: "os", label: "Ossetian" },
  { code: "pa", label: "Panjabi" },
  { code: "pi", label: "Pāli" },
  { code: "fa", label: "Persian" },
  { code: "pl", label: "Polish" },
  { code: "ps", label: "Pashto" },
  { code: "pt", label: "Portuguese" },
  { code: "qu", label: "Quechua" },
  { code: "rm", label: "Romansh" },
  { code: "rn", label: "Kirundi" },
  { code: "ro", label: "Romanian" },
  { code: "ru", label: "Russian" },
  { code: "sa", label: "Sanskrit" },
  { code: "sc", label: "Sardinian" },
  { code: "sd", label: "Sindhi" },
  { code: "se", label: "Northern Sami" },
  { code: "sm", label: "Samoan" },
  { code: "sg", label: "Sango" },
  { code: "sr", label: "Serbian" },
  { code: "gd", label: "Scottish Gaelic" },
  { code: "sn", label: "Shona" },
  { code: "si", label: "Sinhala" },
  { code: "sk", label: "Slovak" },
  { code: "sl", label: "Slovene" },
  { code: "so", label: "Somali" },
  { code: "st", label: "Southern Sotho" },
  { code: "es", label: "Spanish" },
  { code: "su", label: "Sundanese" },
  { code: "sw", label: "Swahili" },
  { code: "ss", label: "Swati" },
  { code: "sv", label: "Swedish" },
  { code: "ta", label: "Tamil" },
  { code: "te", label: "Telugu" },
  { code: "tg", label: "Tajik" },
  { code: "th", label: "Thai" },
  { code: "ti", label: "Tigrinya" },
  { code: "bo", label: "Tibetan" },
  { code: "tk", label: "Turkmen" },
  { code: "tl", label: "Tagalog" },
  { code: "tn", label: "Tswana" },
  { code: "to", label: "Tonga" },
  { code: "tr", label: "Turkish" },
  { code: "ts", label: "Tsonga" },
  { code: "tt", label: "Tatar" },
  { code: "tw", label: "Twi" },
  { code: "ty", label: "Tahitian" },
  { code: "ug", label: "Uyghur" },
  { code: "uk", label: "Ukrainian" },
  { code: "ur", label: "Urdu" },
  { code: "uz", label: "Uzbek" },
  { code: "ve", label: "Venda" },
  { code: "vi", label: "Vietnamese" },
  { code: "vo", label: "Volapük" },
  { code: "wa", label: "Walloon" },
  { code: "cy", label: "Welsh" },
  { code: "wo", label: "Wolof" },
  { code: "xh", label: "Xhosa" },
  { code: "yi", label: "Yiddish" },
  { code: "yo", label: "Yoruba" },
  { code: "za", label: "Zhuang" },
  { code: "zu", label: "Zulu" },
];

export const educationSubCategories = {
  "Arts and Humanities": [
    { label: "History" },
    { label: "Philosophy" },
    { label: "Literature" },
    { label: "Visual Arts" },
    { label: "Performing Arts" },
    { label: "Cultural Studies" },
    { label: "Religious Studies" },
  ],
  "Business and Management": [
    { label: "Accounting" },
    { label: "Finance" },
    { label: "Marketing" },
    { label: "Human Resource Management" },
    { label: "Entrepreneurship" },
    { label: "Operations Management" },
    { label: "Project Management" },
  ],
  "Computer Science and IT": [
    { label: "Software Development" },
    { label: "Cybersecurity" },
    { label: "Artificial Intelligence" },
    { label: "Data Science" },
    { label: "Networking" },
    { label: "Web Development" },
    { label: "IT Support" },
  ],
  "Education and Teaching": [
    { label: "Early Childhood Education" },
    { label: "Primary Education" },
    { label: "Secondary Education" },
    { label: "Special Education" },
    { label: "Educational Leadership" },
    { label: "Curriculum Design" },
  ],
  "Engineering and Technology": [
    { label: "Mechanical Engineering" },
    { label: "Electrical Engineering" },
    { label: "Civil Engineering" },
    { label: "Chemical Engineering" },
    { label: "Computer Engineering" },
    { label: "Robotics" },
    { label: "Mechatronics" },
  ],
  "Health and Medicine": [
    { label: "Medicine" },
    { label: "Nursing" },
    { label: "Pharmacy" },
    { label: "Public Health" },
    { label: "Dentistry" },
    { label: "Nutrition" },
    { label: "Physical Therapy" },
  ],
  "Law and Legal Studies": [
    { label: "Civil Law" },
    { label: "Criminal Law" },
    { label: "International Law" },
    { label: "Corporate Law" },
    { label: "Human Rights Law" },
    { label: "Environmental Law" },
  ],
  "Mathematics and Statistics": [
    { label: "Pure Mathematics" },
    { label: "Applied Mathematics" },
    { label: "Statistics" },
    { label: "Actuarial Science" },
    { label: "Mathematical Modelling" },
  ],
  "Natural Sciences": [
    { label: "Biology" },
    { label: "Chemistry" },
    { label: "Physics" },
    { label: "Earth Sciences" },
    { label: "Astronomy" },
    { label: "Environmental Science" },
  ],
  "Social Sciences": [
    { label: "Sociology" },
    { label: "Anthropology" },
    { label: "Geography" },
    { label: "Political Science" },
    { label: "Criminology" },
  ],
  "Agriculture and Environmental Sciences": [
    { label: "Agronomy" },
    { label: "Horticulture" },
    { label: "Animal Science" },
    { label: "Forestry" },
    { label: "Environmental Management" },
    { label: "Sustainable Agriculture" },
  ],
  "Architecture and Construction": [
    { label: "Architecture" },
    { label: "Urban Planning" },
    { label: "Construction Management" },
    { label: "Structural Design" },
    { label: "Interior Design" },
  ],
  "Communications and Media": [
    { label: "Journalism" },
    { label: "Public Relations" },
    { label: "Media Studies" },
    { label: "Film and Television" },
    { label: "Digital Media" },
  ],
  "Economics and Finance": [
    { label: "Microeconomics" },
    { label: "Macroeconomics" },
    { label: "Banking" },
    { label: "Investment" },
    { label: "Financial Planning" },
  ],
  "Hospitality and Tourism": [
    { label: "Hotel Management" },
    { label: "Travel and Tourism" },
    { label: "Event Management" },
    { label: "Culinary Arts" },
  ],
  "Languages and Linguistics": [
    { label: "Applied Linguistics" },
    { label: "Translation and Interpretation" },
    { label: "Foreign Languages" },
    { label: "Syntax and Semantics" },
  ],
  "Philosophy and Religion": [
    { label: "Ethics" },
    { label: "Metaphysics" },
    { label: "World Religions" },
    { label: "Theology" },
  ],
  "Political Science and International Relations": [
    { label: "Comparative Politics" },
    { label: "International Politics" },
    { label: "Public Policy" },
    { label: "Global Studies" },
  ],
  Psychology: [
    { label: "Clinical Psychology" },
    { label: "Counseling Psychology" },
    { label: "Developmental Psychology" },
    { label: "Cognitive Psychology" },
    { label: "Industrial-Organizational Psychology" },
  ],
  "Public Administration and Policy": [
    { label: "Public Policy" },
    { label: "Government Administration" },
    { label: "Urban Affairs" },
    { label: "Nonprofit Management" },
  ],
  "Vocational and Technical Education": [
    { label: "Welding" },
    { label: "Plumbing" },
    { label: "Automotive Technology" },
    { label: "Electrical Installation" },
    { label: "Carpentry" },
  ],
  "Sports and Physical Education": [
    { label: "Sports Coaching" },
    { label: "Physical Fitness" },
    { label: "Kinesiology" },
    { label: "Recreational Therapy" },
  ],
  "Transportation and Logistics": [
    { label: "Supply Chain Management" },
    { label: "Logistics" },
    { label: "Maritime Transportation" },
    { label: "Aviation Management" },
  ],
};
